// flow-typed signature: 6ab968b00103dbf0b43073a39f48780b
// flow-typed version: <<STUB>>/sharp-cli_v^1.10.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sharp-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sharp-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sharp-cli/bin/cli' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/channel-manipulation/bandbool' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/channel-manipulation/ensure-alpha' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/channel-manipulation/extract' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/channel-manipulation/join' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/channel-manipulation/remove-alpha' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/colour-manipulation/greyscale' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/colour-manipulation/tint' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/colour-manipulation/tocolourspace' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/compositing/composite' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/compositing/overlay-with' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/operations/blur' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/operations/boolean' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/operations/convolve' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/operations/flatten' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/operations/flip' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/operations/flop' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/operations/gamma' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/operations/linear' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/operations/median' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/operations/modulate' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/operations/negate' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/operations/normalise' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/operations/recomb' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/operations/rotate' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/operations/sharpen' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/operations/threshold' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/output' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/resize' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/resizing/extend' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/resizing/extract' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/resizing/resize' {
  declare module.exports: any;
}

declare module 'sharp-cli/cmd/resizing/trim' {
  declare module.exports: any;
}

declare module 'sharp-cli/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'sharp-cli/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'sharp-cli/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'sharp-cli/lib/cli' {
  declare module.exports: any;
}

declare module 'sharp-cli/lib/constants' {
  declare module.exports: any;
}

declare module 'sharp-cli/lib/convert' {
  declare module.exports: any;
}

declare module 'sharp-cli/lib/index' {
  declare module.exports: any;
}

declare module 'sharp-cli/lib/queue' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sharp-cli/bin/cli.js' {
  declare module.exports: $Exports<'sharp-cli/bin/cli'>;
}
declare module 'sharp-cli/cmd/channel-manipulation/bandbool.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/channel-manipulation/bandbool'>;
}
declare module 'sharp-cli/cmd/channel-manipulation/ensure-alpha.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/channel-manipulation/ensure-alpha'>;
}
declare module 'sharp-cli/cmd/channel-manipulation/extract.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/channel-manipulation/extract'>;
}
declare module 'sharp-cli/cmd/channel-manipulation/join.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/channel-manipulation/join'>;
}
declare module 'sharp-cli/cmd/channel-manipulation/remove-alpha.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/channel-manipulation/remove-alpha'>;
}
declare module 'sharp-cli/cmd/colour-manipulation/greyscale.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/colour-manipulation/greyscale'>;
}
declare module 'sharp-cli/cmd/colour-manipulation/tint.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/colour-manipulation/tint'>;
}
declare module 'sharp-cli/cmd/colour-manipulation/tocolourspace.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/colour-manipulation/tocolourspace'>;
}
declare module 'sharp-cli/cmd/compositing/composite.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/compositing/composite'>;
}
declare module 'sharp-cli/cmd/compositing/overlay-with.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/compositing/overlay-with'>;
}
declare module 'sharp-cli/cmd/operations/blur.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/operations/blur'>;
}
declare module 'sharp-cli/cmd/operations/boolean.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/operations/boolean'>;
}
declare module 'sharp-cli/cmd/operations/convolve.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/operations/convolve'>;
}
declare module 'sharp-cli/cmd/operations/flatten.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/operations/flatten'>;
}
declare module 'sharp-cli/cmd/operations/flip.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/operations/flip'>;
}
declare module 'sharp-cli/cmd/operations/flop.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/operations/flop'>;
}
declare module 'sharp-cli/cmd/operations/gamma.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/operations/gamma'>;
}
declare module 'sharp-cli/cmd/operations/linear.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/operations/linear'>;
}
declare module 'sharp-cli/cmd/operations/median.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/operations/median'>;
}
declare module 'sharp-cli/cmd/operations/modulate.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/operations/modulate'>;
}
declare module 'sharp-cli/cmd/operations/negate.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/operations/negate'>;
}
declare module 'sharp-cli/cmd/operations/normalise.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/operations/normalise'>;
}
declare module 'sharp-cli/cmd/operations/recomb.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/operations/recomb'>;
}
declare module 'sharp-cli/cmd/operations/rotate.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/operations/rotate'>;
}
declare module 'sharp-cli/cmd/operations/sharpen.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/operations/sharpen'>;
}
declare module 'sharp-cli/cmd/operations/threshold.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/operations/threshold'>;
}
declare module 'sharp-cli/cmd/output.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/output'>;
}
declare module 'sharp-cli/cmd/resize.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/resize'>;
}
declare module 'sharp-cli/cmd/resizing/extend.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/resizing/extend'>;
}
declare module 'sharp-cli/cmd/resizing/extract.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/resizing/extract'>;
}
declare module 'sharp-cli/cmd/resizing/resize.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/resizing/resize'>;
}
declare module 'sharp-cli/cmd/resizing/trim.js' {
  declare module.exports: $Exports<'sharp-cli/cmd/resizing/trim'>;
}
declare module 'sharp-cli/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'sharp-cli/coverage/lcov-report/block-navigation'>;
}
declare module 'sharp-cli/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'sharp-cli/coverage/lcov-report/prettify'>;
}
declare module 'sharp-cli/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'sharp-cli/coverage/lcov-report/sorter'>;
}
declare module 'sharp-cli/lib/cli.js' {
  declare module.exports: $Exports<'sharp-cli/lib/cli'>;
}
declare module 'sharp-cli/lib/constants.js' {
  declare module.exports: $Exports<'sharp-cli/lib/constants'>;
}
declare module 'sharp-cli/lib/convert.js' {
  declare module.exports: $Exports<'sharp-cli/lib/convert'>;
}
declare module 'sharp-cli/lib/index.js' {
  declare module.exports: $Exports<'sharp-cli/lib/index'>;
}
declare module 'sharp-cli/lib/queue.js' {
  declare module.exports: $Exports<'sharp-cli/lib/queue'>;
}
